using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CommonFrontEnd.Constants
{
    public class BowServletsConstants
    {
        public static string WEBAPPPATH = "../ppfp";
        public static string JSPATH = "/order/scripts";
        public static string CSSPATH = "/order/scripts";
        public static string PARAMROWCOUNT = "rowcount";
        public static string PARAMORDERID = "orderid";
        public static string ATTRIBUTEORDERBEAN = "orderbean";
        public static string ATTRIBUTEORDERS = "orders";
        public static string PARAMORDERTABLENAME = "ordertablename";
        public static string PARAMORDERDIRECTION = "orderdirection";
        public static string PARAMORDERSOURCE = "ordersource";
        public static string PARAMORDERDESTINATION = "orderdestination";
        public static string PARAMORDERSEGMENT = "ordersegment";
        public static string PARAMORDERNSETOKEN = "ordernsetoken";
        public static string PARAMORDERBSETOKEN = "orderbsetoken";
        public static string PARAMORDERTOKEN = "ordertoken";
        public static string PARAMORDERSYMBOL = "ordersymbol";
        public static string PARAMORDERSERIES = "orderseries";
        public static string PARAMORDERGTC = "GTC";
        public static string PARAMORDERIOC = "IOC";
        public static string PARAMORDERCURRENTPOSITIONID = "ordercurrentpositionid";
        public static string ATTRIBUTEORDERCURRENTPOSITIONBEAN = "ordercurrentpositionbean";
        public static string ATTRIBUTEORDERCURRENTPOSITIONS = "ordercurrentpositions";
        public static string PARAMORDERCURRENTPOSITIONUSID = "ordercurrentpositionusid";
        public static string PARAMORDERCURRENTPOSITIONEXID = "ordercurrentpositionexid";
        public static string PARAMORDERCURRENTPOSITIONSEGMENTID = "ordercurrentpositionsegmentid";
        public static string PARAMORDERCURRENTPOSITIONTOKEN = "ordercurrentpositiontoken";
        public static string PARAMORDERCURRENTPOSITIONNSETOKEN = "ordercurrentpositionnsetoken";
        public static string PARAMORDERCURRENTPOSITIONBSETOKEN = "ordercurrentpositionbsetoken";
        public static string PARAMORDERCURRENTPOSITIONSYMBOL = "ordercurrentpositionsymbol";
        public static string PARAMORDERCURRENTPOSITIONSERIES = "ordercurrentpositionseries";
        public static string PARAMSPREADORDERID = "spreadorderid";
        public static string ATTRIBUTESPREADORDERBEAN = "spreadorderbean";
        public static string ATTRIBUTESPREADORDERS = "spreadorders";
        public static string PARAMEXERCISEID = "exerciseid";
        public static string ATTRIBUTEEXERCISEBEAN = "exercisebean";
        public static string ATTRIBUTEEXERCISES = "exercises";
        public static string PARAMEXERCISEMESSAGEID = "exercisemessageid";
        public static string PARAMEXERCISETABLENAME = "exercisetablename";
        public static string PARAMTRADEID = "tradeid";
        public static string ATTRIBUTETRADEBEAN = "tradebean";
        public static string ATTRIBUTETRADES = "trades";
        public static string PARAMTRADETABLENAME = "tradetablename";
        public static string PARAMTRADEDIRECTION = "tradedirection";
        public static string PARAMTRADESOURCE = "tradesource";
        public static string PARAMTRADEDESTINATION = "tradedestination";
        public static string PARAMTRADESEGMENT = "tradesegment";
        public static string PARAMTRADEMARKET = "trademarket";
        public static string PARAMORDERMARKET = "ordermarket";
        public static string PARAMTRADENSETOKEN = "tradensetoken";
        public static string PARAMTRADEBSETOKEN = "tradebsetoken";
        public static string PARAMTRADETOKEN = "tradetoken";
        public static string PARAMSPREADORDERMESSAGEID = "spreadordermessageid";
        public static string PARAMSPREADORDERTABLENAME = "spreadordertablename";
        public static string PARAMSPREADORDERDIRECTION = "spreadorderdirection";
        public static string PARAMSPREADORDERSOURCE = "spreadordersource";
        public static string PARAMSPREADORDERDESTINATION = "spreadorderdestination";
        public static string PARAMSPREADORDERSEGMENT = "spreadordersegment";
        public static string PARAMSPREADORDERNSETOKEN = "spreadordernsetoken";
        public static string PARAMSPREADORDERBSETOKEN = "spreadorderbsetoken";
        public static string PARAMBULKORDERMODE = "mode";
        public static string PARAMBULKORDERMODEUPLOAD = "upload";
        public static string PARAMBULKORDERMODERELEASE = "release";
        public static string PARAMBULKORDERFILEDATA = "filedata";

        public static readonly string URL_ADD_EXERCISE = "/AddExercise";
        public static readonly string URL_ADD_ORDER = "/AddOrder";
        public static readonly string URL_ADD_SOR_ORDER = "/AddSOROrder";
        public static readonly string URL_ADD_ORDER_CURRENT_POSITION = "/AddOrderCurrentPosition";
        public static readonly string URL_ADD_SPREAD_ORDER = "/AddSpreadOrder";
        public static readonly string URL_ADD_TRADE = "/AddTrade";
        public static readonly string URL_DELETE_EXERCISE = "/DeleteExercise";
        public static readonly string URL_DELETE_ORDER = "/DeleteOrder";
        public static readonly string URL_DELETE_ORDER_CURRENT_POSITION = "/DeleteOrderCurrentPosition";
        public static readonly string URL_DELETE_SPREAD_ORDER = "/DeleteSpreadOrder";
        public static readonly string URL_DELETE_TRADE = "/DeleteTrade";
        public static readonly string URL_EDIT_EXERCISE = "/EditExercise";
        public static readonly string URL_EDIT_EXERCISES = "/EditExercises";
        public static readonly string URL_EDIT_ORDER = "/EditOrder";
        public static readonly string URL_EDIT_ORDER_CURRENT_POSITION = "/EditOrderCurrentPosition";
        public static readonly string URL_EDIT_ORDER_CURRENT_POSITIONS = "/EditOrderCurrentPositions";
        public static readonly string URL_EDIT_ORDERS = "/EditOrders";
        public static readonly string URL_EDIT_SPREAD_ORDER = "/EditSpreadOrder";
        public static readonly string URL_EDIT_SPREAD_ORDERS = "/EditSpreadOrders";
        public static readonly string URL_EDIT_TRADE = "/EditTrade";
        public static readonly string URL_EDIT_TRADES = "/EditTrades";
        public static readonly string URL_LIST_EXERCISE = "/ListExercise";
        public static readonly string URL_LIST_ORDER = "/ListOrder";
        public static readonly string URL_LIST_OFSORDER = "/ListBulkOrders_OFS";
        public static readonly string URL_LIST_ORDER_CURRENT_POSITION = "/ListOrderCurrentPosition";
        public static readonly string URL_LIST_SPREAD_ORDER = "/ListSpreadOrder";
        public static readonly string URL_LIST_TRADE = "/ListTrade";
        public static readonly string URL_LIST_INSTITUTIONAL_TRADE = "/ListInstitutionalTrades";
        public static readonly string URL_LIST_AUCTION = "/ListAuctions";
        public static readonly string URL_PRE_ADD_EXERCISE = "/PreAddExercise";
        public static readonly string URL_PRE_ADD_ORDER = "/PreAddOrder";
        public static readonly string URL_PRE_ADD_ORDER_CURRENT_POSITION = "/PreAddOrderCurrentPosition";
        public static readonly string URL_PRE_ADD_SPREAD_ORDER = "/PreAddSpreadOrder";
        public static readonly string URL_PRE_ADD_TRADE = "/PreAddTrade";
        public static readonly string URL_PRE_EDIT_EXERCISE = "/PreEditExercise";
        public static readonly string URL_PRE_EDIT_EXERCISES = "/PreEditExercises";
        public static readonly string URL_PRE_EDIT_ORDER = "/PreEditOrder";
        public static readonly string URL_PRE_EDIT_ORDER_CURRENT_POSITION = "/PreEditOrderCurrentPosition";
        public static readonly string URL_PRE_EDIT_ORDER_CURRENT_POSITIONS = "/PreEditOrderCurrentPositions";
        public static readonly string URL_PRE_EDIT_ORDERS = "/PreEditOrders";
        public static readonly string URL_PRE_EDIT_SPREAD_ORDER = "/PreEditSpreadOrder";
        public static readonly string URL_PRE_EDIT_SPREAD_ORDERS = "/PreEditSpreadOrders";
        public static readonly string URL_PRE_EDIT_TRADE = "/PreEditTrade";
        public static readonly string URL_PRE_EDIT_TRADES = "/PreEditTrades";
        public static readonly string URL_VIEW_EXERCISE = "/ViewExercise";
        public static readonly string URL_VIEW_ORDER = "/ViewOrder";
        public static readonly string URL_VIEW_ORDER_CURRENT_POSITION = "/ViewOrderCurrentPosition";
        public static readonly string URL_VIEW_SPREAD_ORDER = "/ViewSpreadOrder";
        public static readonly string URL_VIEW_TRADE = "/ViewTrade";
        public static readonly string URL_LIST_ACTIVITYLOG = "/ListActivityLog";
        public static readonly string URL_DELTA_DOWNLOAD_ORDERS = "/DeltaDownloadOrders";
        public static readonly string URL_DELTA_DOWNLOAD_TRADES = "/DeltaDownloadTrades";
        public static readonly string URL_GET_ORDER_IMAGE = "/GetLatestOrderImage";
        public static readonly string URL_LIST_UNSENT_ORDERS = "/ListUnsentOrders";
        public static readonly string URL_LIST_BHAVCOPY = "/ListBhavCopy";
        public static readonly string URL_UPLOAD_BULK_ORDERS = "/UploadBulkOrders";
        public static readonly string URL_ORDER_TRADE_SUMMARY = "/ListOrderTradeSummary";

    }
}
